### ISSUE TITLE
how do I upgrade?

### ISSUE THREAD

**Issue by LordAmit** [dyndna/lanyon-plus#6]
Been using Lanyon-plus from v1.1.0. Seems like you made changes  in v1.1.1.
However, I also made changes in my version - making changes here and there.

How do I upgrade to the latest version without breaking? 

(if this is a trivial question, please at least give me a link :D )

**Comment by dyndna** [comment]
Glad that you are using lanyon-plus theme. v1.1.1 has a few changes in backend with compatibility for Jekyll v >= 3.0 as github recently moved to jekyll 3.0 <sup>[1](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)</sup> There are not many changes in website layout or features. Unless github build on your website is showing error, you may not need to update it. Jekyll 3.0 also comes with some bugs and hopefully will be fixed in coming releases. <sup>[2](https://github.com/dyndna/lanyon-plus/releases/tag/v1.1.1)</sup>

If you want to merge from upstream: dyndna/lanyon-plus to your website given you also made some changes, please follow github steps:
1. https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/
2. https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

If you prefer GUI over terminal for resolving conflicts and keeping your edits, there are some GUI tools with good merge editors, https://www.gitkraken.com and http://www.syntevo.com/smartgit/
